const projectData = [
  {
    id: 1,
    company: "Fresh Cart | Ecommerce",
    date: "March 2024",
    description: `Developed Fresh Cart, a robust eCommerce platform designed to enhance online shopping experiences. Leveraged Vue.js and TypeScript to create a user-friendly interface, while Node.js and Express were used for backend services. Emphasized responsive design principles using HTML5 and CSS3 to ensure a seamless shopping experience, focusing on efficient product management and a streamlined checkout process.`,
    skills: ["Vue.js", "Node.js", "TypeScript", "JavaScript", "Express", "HTML5", "CSS3"],
    image: "/fakhrialfi9/image/freshcart.jpg",
    website: "#",
  },
  {
    id: 2,
    company: "Skyline Sanctuary | Real Estate",
    date: "October 2023",
    description: `Developed a comprehensive real estate website for Skyline Sanctuary to display properties and provide valuable information to potential buyers. Utilized React.js and Vite.js to build a modern, high-performance frontend. Features include property listings, advanced search capabilities, and a user-friendly interface, all crafted with HTML5 and CSS3 to ensure an engaging user experience.`,
    skills: ["React.js", "Vite.js", "JavaScript", "HTML5", "CSS3"],
    image: "/fakhrialfi9/image/skylinesanctuary.jpg",
    website: "#",
  },
  {
    id: 3,
    company: "Emerald Cilebut | Real Estate",
    date: "October 2023",
    description: `Designed and developed a dynamic real estate platform for Emerald Cilebut. The site features detailed property listings and a sleek, responsive design built with React.js and Vite.js. Focused on creating a fast, user-friendly experience with HTML5 and CSS3 to effectively showcase properties and attract potential buyers.`,
    skills: ["React.js", "Vite.js", "JavaScript", "HTML5", "CSS3"],
    image: "/fakhrialfi9/image/emeraldcilebut.jpg",
    website: "#",
  },
  {
    id: 4,
    company: "Blessing CCTV | Company Profile",
    date: "August 2023",
    description: `Developed a professional company profile website for Blessing CCTV using WordPress and Elementor. The site features a clean and elegant design with an easy-to-navigate layout, highlighting the company's CCTV solutions and services. Emphasized creating a strong online presence that effectively communicates the company’s expertise in security solutions.`,
    skills: ["WordPress", "Elementor"],
    image: "/fakhrialfi9/image/blessingcctv.jpg",
    website: "#",
  },
  {
    id: 5,
    company: "Al - Azhar Syifa Budi Cibubur | Primary School",
    date: "January 2024",
    description: `Designed and developed an engaging website for Al - Azhar Syifa Budi Cibubur Primary School. The site features a user-friendly interface and modern design elements using React.js and Vite.js. The platform includes essential information about the school, events, and educational resources, crafted with HTML5 and CSS3 to enhance the school's online presence and communication.`,
    skills: ["React.js", "Vite.js", "JavaScript", "HTML5", "CSS3"],
    image: "/fakhrialfi9/image/alazharsyifabudi.jpg",
    website: "#",
  },
  {
    id: 6,
    company: "Code Crafters | Code Template",
    date: "September 2023",
    description: `Created a versatile code template for Code Crafters, focusing on clean and efficient design principles using WordPress and Elementor. The template is designed to be easily customizable, featuring a modern look and user-friendly layout. It is intended for developers and businesses looking to quickly deploy professional websites with a polished appearance.`,
    skills: ["WordPress", "Elementor"],
    image: "/fakhrialfi9/image/codecrafters.jpg",
    website: "#",
  },
];

export default projectData;
